namespace ImeWlConverter.SourceGenerators;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class FormatRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with [FormatPlugin] attribute
        var formatClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ImeWlConverter.Abstractions.FormatPluginAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetFormatInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // Collect all format info
        var collected = formatClasses.Collect();

        // Generate the registration code
        context.RegisterSourceOutput(collected, static (spc, formats) =>
        {
            if (formats.IsEmpty) return;
            var source = GenerateRegistrationCode(formats);
            spc.AddSource("FormatRegistry.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static FormatInfo? GetFormatInfo(GeneratorAttributeSyntaxContext context)
    {
        var symbol = context.TargetSymbol as INamedTypeSymbol;
        if (symbol == null) return null;

        var attr = context.Attributes.FirstOrDefault();
        if (attr == null) return null;

        var id = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value?.ToString() ?? ""
            : "";
        var displayName = attr.ConstructorArguments.Length > 1
            ? attr.ConstructorArguments[1].Value?.ToString() ?? ""
            : "";

        var isImporter = symbol.AllInterfaces.Any(i =>
            i.ToDisplayString() == "ImeWlConverter.Abstractions.Contracts.IFormatImporter");
        var isExporter = symbol.AllInterfaces.Any(i =>
            i.ToDisplayString() == "ImeWlConverter.Abstractions.Contracts.IFormatExporter");

        return new FormatInfo(
            symbol.ToDisplayString(),
            id,
            displayName,
            isImporter,
            isExporter);
    }

    private static string GenerateRegistrationCode(ImmutableArray<FormatInfo> formats)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ImeWlConverter.Abstractions.Contracts;");
        sb.AppendLine();
        sb.AppendLine("namespace ImeWlConverter.Formats;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated format registration. Discovered " + formats.Length + " format plugins.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class FormatRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Register all discovered format importers and exporters.</summary>");
        sb.AppendLine("    public static IServiceCollection AddAllFormats(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var format in formats)
        {
            if (format.IsImporter)
                sb.AppendLine($"        services.AddSingleton<IFormatImporter, {format.FullTypeName}>();");
            if (format.IsExporter)
                sb.AppendLine($"        services.AddSingleton<IFormatExporter, {format.FullTypeName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct FormatInfo
    {
        public string FullTypeName { get; }
        public string Id { get; }
        public string DisplayName { get; }
        public bool IsImporter { get; }
        public bool IsExporter { get; }

        public FormatInfo(string fullTypeName, string id, string displayName, bool isImporter, bool isExporter)
        {
            FullTypeName = fullTypeName;
            Id = id;
            DisplayName = displayName;
            IsImporter = isImporter;
            IsExporter = isExporter;
        }
    }
}
